# Generated by Django 5.2.3 on 2025-07-30 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'permissions': [('can_unpublish_product', 'Может отменять публикацию продукта'), ('can_change_publish_status', 'Может менять статус публикации')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('moderation', 'На модерации'), ('rejected', 'Отклонено')], default='moderation', max_length=20, verbose_name='Статус публикации'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_category_name'),
        ),
    ]
